export const COLOR = {
    LIGHT_GRAPEFRUIT: '#FF8A8A',
    GRAPEFRUIT: '#FF5A5A',
    DARK_GRAPEFRUIT: '#CE3838',

    GREEN_TEAL: '#2ECC71',
    
    LIGHT_GREEN_BLUE: '#8ED9CC',
    GREEN_BLUE: '#48B6A3',
    DARK_GREEN_BLUE: '#479D8E',

    LIGHTER_GREY: '#D8D8D8',
    LIGHT_GREY: '#9B9B9B',
    GREY: '#5F5F5F',
    DARK_GREY: '#4A4A4A',
}